// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/plimble/unik (interfaces: Generator)

package mock_unik

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Generator interface
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *_MockGeneratorRecorder
}

// Recorder for MockGenerator (not exported)
type _MockGeneratorRecorder struct {
	mock *MockGenerator
}

func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &_MockGeneratorRecorder{mock}
	return mock
}

func (_m *MockGenerator) EXPECT() *_MockGeneratorRecorder {
	return _m.recorder
}

func (_m *MockGenerator) Generate() string {
	ret := _m.ctrl.Call(_m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockGeneratorRecorder) Generate() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Generate")
}
